[package]
name = "carcara"
version = "0.1.0"
authors = ["Bruno Andreotti <bandreotti@protonmail.com>"]
edition = "2021"
rust-version = "1.61"
license = "Apache-2.0"

[dependencies]
ahash = "0.7.4"
log = "0.4.14"
rug = { version = "1.16.0", features = ["integer", "rational"] }
thiserror = "1.0.30"
crossbeam = "0.8"

[features]
large-test-set = []

[dev-dependencies]
rand = "0.8.4"
